/**
 * spark-html-offline — URL-imported components that survive a dead CDN.
 *
 * The #1 critique of `<div import="https://esm.sh/…/card.html">` is
 * "CDN down = component gone". This package is a tiny service worker
 * that caches those cross-origin fetches on first load and serves them
 * cache-first afterwards (refreshing in the background), so a component
 * imported by URL keeps working when the CDN is slow, flaky, or the
 * user is offline.
 *
 *   // main.js — zero config
 *   import { offline } from 'spark-html-offline';
 *   offline();
 *
 *   // spark.config.js — writes + serves the worker file for you
 *   import offlineSw from 'spark-html-offline/bun';
 *   plugins: [spark(), offlineSw()]
 *
 * Works with any CDN (esm.sh, unpkg, jsdelivr, your own). By default it
 * ONLY handles cross-origin GETs — local dev files are never intercepted,
 * so dev servers and HMR behave exactly as before. Same-origin paths can
 * opt in via `include` (e.g. `include: ['/components/']` to make your own
 * fragments offline-capable too).
 *
 * No build step? Write the worker once with `swSource()` (or copy it from
 * the README), host it next to index.html, and call `offline()`.
 */

/** Cache name — bump the suffix to invalidate everything on upgrade. */
export const CACHE_NAME = 'spark-offline-v1';

/**
 * Decide whether the worker should handle a URL.
 * Cross-origin http(s) → yes (the CDN-import case), unless excluded.
 * Same-origin → only when it matches an `include` substring.
 * This exact function is embedded into the generated worker.
 */
export function shouldHandle(url, origin, config) {
  var u;
  try { u = new URL(url); } catch (e) { return false; }
  if (u.protocol !== 'http:' && u.protocol !== 'https:') return false;
  var cfg = config || {};
  var i;
  for (i = 0; i < (cfg.exclude || []).length; i++) {
    if (url.indexOf(cfg.exclude[i]) !== -1) return false;
  }
  if (u.origin !== origin) return true;
  for (i = 0; i < (cfg.include || []).length; i++) {
    if (url.indexOf(cfg.include[i]) !== -1) return true;
  }
  return false;
}

/**
 * The service-worker source, as a string — write it to a file served from
 * your origin (the bun build step does this for you as /spark-sw.js).
 *
 * Strategy: cache-first with background revalidation (stale-while-
 * revalidate). First visit fetches + caches; every visit after serves
 * from cache instantly and refreshes the entry in the background, so
 * users are never more than one visit behind — and never broken.
 *
 * @param {object} [options]
 * @param {string[]} [options.include] Same-origin URL substrings to cache too.
 * @param {string[]} [options.exclude] URL substrings to never touch.
 * @param {string}   [options.cacheName] Override the cache bucket name.
 */
export function swSource(options = {}) {
  const config = JSON.stringify({
    include: options.include || [],
    exclude: options.exclude || [],
  });
  const cache = JSON.stringify(options.cacheName || CACHE_NAME);
  return `/* generated by spark-html-offline — cache-first for URL imports */
'use strict';
var CACHE = ${cache};
var CONFIG = ${config};
var shouldHandle = ${shouldHandle.toString()};

self.addEventListener('install', function () { self.skipWaiting(); });
self.addEventListener('activate', function (event) {
  event.waitUntil(self.clients.claim());
});
self.addEventListener('fetch', function (event) {
  var req = event.request;
  if (req.method !== 'GET') return;
  if (req.url.indexOf('/__spark/') !== -1) return; // server SSE channels — streams, never cache
  if (!shouldHandle(req.url, self.location.origin, CONFIG)) return;
  event.respondWith(caches.open(CACHE).then(function (cache) {
    return cache.match(req).then(function (cached) {
      var refresh = fetch(req).then(function (res) {
        // Never cache streams or no-store responses — Cache.put() on an
        // endless event-stream rejects with a NetworkError.
        var ct = (res && res.headers.get('content-type')) || '';
        var cc = (res && res.headers.get('cache-control')) || '';
        var cachable = res && res.ok
          && ct.indexOf('text/event-stream') === -1
          && cc.indexOf('no-store') === -1;
        // A request aborted mid-stream (the user navigated away) leaves the
        // cloned body in a network-error state, so Cache.put() rejects — a
        // harmless race, but an unhandled rejection without this catch.
        if (cachable) cache.put(req, res.clone()).catch(function () {});
        return res;
      }).catch(function () { return null; });
      if (cached) {
        // Serve instantly; keep the worker alive while the refresh lands.
        event.waitUntil(refresh);
        return cached;
      }
      return refresh.then(function (fresh) {
        return fresh || new Response('', { status: 504, statusText: 'offline and never cached' });
      });
    });
  }));
});
`;
}

/**
 * Register the worker. Call once from main.js. No-ops safely where
 * service workers don't exist (prerender, old browsers, non-secure
 * origins) — your app runs exactly as before, just without the net.
 *
 * @param {object} [options]
 * @param {string} [options.sw='spark-sw.js'] Worker URL (relative to the page base).
 * @param {string} [options.scope] Registration scope (default: the worker's directory).
 * @returns {Promise<ServiceWorkerRegistration|null>}
 */
export async function offline(options = {}) {
  if (typeof navigator === 'undefined' || !navigator.serviceWorker) return null;
  if (typeof globalThis.__SPARK_PRERENDER__ !== 'undefined' && globalThis.__SPARK_PRERENDER__) return null;
  const sw = options.sw || 'spark-sw.js';
  try {
    return await navigator.serviceWorker.register(sw, options.scope ? { scope: options.scope } : undefined);
  } catch (e) {
    console.warn(`[spark-offline] service worker registration failed: ${e.message}`);
    return null;
  }
}

export default { offline, swSource, shouldHandle, CACHE_NAME };
