import { store } from "spark-html";
// @spark:!router
import { mount } from "spark-html";
// @spark:end
// @spark:router
import { router } from "spark-html-router";
// @spark:end
// @spark:theme
import { theme } from "spark-html-theme";
// @spark:end
import { head } from "spark-html-head";
import { persist } from "spark-html-persist";
// @spark:sri
import { sri } from "spark-html-sri";
// @spark:end
import { devtools } from "spark-html-devtools";

const dev = import.meta.env?.DEV;
if (dev) devtools(); // dev only

// @spark:sri
// Subresource Integrity: verifies every component fetch against the
// manifest the build baked into the page, and allow-lists remote URL
// imports (TOFU). Fails open on localhost, enforces in production.
sri();
// @spark:end

head({
  title: { "/": "Home", "/about": "About", "*": "Not found" },
  titleTemplate: (t) => `${t} · My Site`,
  meta: { description: (path) => `The ${path} page` },
});

// Shared stores connect components without providers or prop drilling.
store("app", { sparks: 0 });

// A store that survives reloads — hydrates from localStorage on boot,
// saves on every change (see components/demo-persist.html).
persist("prefs", { name: "", visits: 0 });

// @spark:theme
// One-line dark/light/system theming (the ⚡ logo toggles it).
theme();
// @spark:end

// @spark:pwa
// PWA: manifest.webmanifest, icons, and the offline app-shell worker are
// generated by spark-html-manifest/vite (see vite.config.js) — the worker
// registration is injected into every built page automatically.
// Want offline-capable CDN component imports too? See spark-html-offline
// (a page registers one worker per scope, so pick the one you need).
// @spark:end

// @spark:router
// Client-side router: reads <template route> blocks, intercepts <a> clicks,
// and manages SPA navigation. Call it once — replaces mount().
router({ devOverlay: dev, quiet: !dev });
// @spark:end
// @spark:!router
mount(document.body);
// @spark:end
