/**
 * Compute the hero stats from the live source, so they NEVER go stale — the
 * same numbers main.js seeds into the `stats` store (dev) and the build bakes
 * into the prerendered home page. Run before `spark dev` / `spark build`:
 *
 *   bun scripts/gen-stats.js   # writes website/src/stats.js
 *
 * Uses Bun.build (not esbuild) to bundle + minify the runtime for the gzip
 * metric — the same measure as scripts/size-check.mjs — so the website has no
 * bundler dependency of its own.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { gzipSync } from 'node:zlib';

const ROOT = resolve(import.meta.dir, '..', '..');

export async function computeStats() {
  // runtime: gzip of the minified runtime — the same metric as size-check.
  const out = await Bun.build({
    entrypoints: [resolve(ROOT, 'packages/spark/src/index.js')],
    minify: true,
    format: 'esm',
  });
  const code = await out.outputs[0].text();
  const runtimeKb = Math.round(gzipSync(Buffer.from(code)).length / 1024);

  const pkg = JSON.parse(readFileSync(resolve(ROOT, 'packages/spark/package.json'), 'utf8'));
  const deps = Object.keys(pkg.dependencies || {}).length;
  const pkgDirs = readdirSync(resolve(ROOT, 'packages'))
    .filter((d) => existsSync(resolve(ROOT, 'packages', d, 'package.json')));

  // tests: count assertions (`assert(` / `assert.method(`) across every test
  // dir — captures all files, including those with a custom harness. Floored to
  // a tens boundary so the "N+ tests" claim is always honest, never overstated.
  let tests = 0;
  for (const d of pkgDirs) {
    const tdir = resolve(ROOT, 'packages', d, 'test');
    if (!existsSync(tdir)) continue;
    for (const f of readdirSync(tdir)) {
      if (f.endsWith('.js')) tests += (readFileSync(resolve(tdir, f), 'utf8').match(/\bassert(\.\w+)?\(/g) || []).length;
    }
  }

  return { build: 0, runtimeKb, deps, packages: pkgDirs.length, tests: Math.floor(tests / 10) * 10 };
}

if (import.meta.main) {
  const stats = await computeStats();
  // A .js module (not .json) so the dev server serves it to the browser with
  // no JSON import-attribute dance, and the bundler inlines it either way.
  writeFileSync(
    resolve(import.meta.dir, '..', 'src', 'stats.js'),
    `// Generated by scripts/gen-stats.js — do not edit.\nexport default ${JSON.stringify(stats)};\n`,
  );
  console.log('[gen-stats]', JSON.stringify(stats));
}
