/**
 * Compute the hero stats from the live source, so they NEVER go stale — the
 * same numbers main.js seeds into the `stats` store (dev) and the build bakes
 * into the prerendered home page. Run before `spark dev` / `spark build`:
 *
 *   bun scripts/gen-stats.js   # writes website/src/stats.js
 *
 * The gzip metric comes from running scripts/size-check.mjs itself (under
 * node) and parsing its output — the budget gate is the single source of
 * truth for the runtime size, everywhere it is quoted.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';


const ROOT = resolve(import.meta.dir, '..', '..');

export async function computeStats() {
  // runtime: THE number from scripts/size-check.mjs — the budget gate is the
  // single source of truth, so the website chip, the READMEs, and the gate
  // can never disagree. (Bun.build minifies worse than esbuild and Bun's
  // gzipSync compresses differently than Node's — both skewed the chip:
  // 18 and 17.4 vs the gate's 17.24 — so we run the gate itself under node.)
  const gate = Bun.spawnSync(['node', resolve(ROOT, 'scripts/size-check.mjs')]);
  const m = gate.stdout.toString().match(/([\d.]+) KB gzip/);
  if (!m) throw new Error('gen-stats: could not read the gzip size from scripts/size-check.mjs output');
  const runtimeKb = +m[1];

  const pkg = JSON.parse(readFileSync(resolve(ROOT, 'packages/spark/package.json'), 'utf8'));
  const deps = Object.keys(pkg.dependencies || {}).length;
  const pkgDirs = readdirSync(resolve(ROOT, 'packages'))
    .filter((d) => existsSync(resolve(ROOT, 'packages', d, 'package.json')));

  // tests: count assertions (`assert(` / `assert.method(`) across every test
  // dir — captures all files, including those with a custom harness. Floored to
  // a tens boundary so the "N+ tests" claim is always honest, never overstated.
  let tests = 0;
  for (const d of pkgDirs) {
    const tdir = resolve(ROOT, 'packages', d, 'test');
    if (!existsSync(tdir)) continue;
    for (const f of readdirSync(tdir)) {
      if (f.endsWith('.js')) tests += (readFileSync(resolve(tdir, f), 'utf8').match(/\bassert(\.\w+)?\(/g) || []).length;
    }
  }

  return { build: 0, runtimeKb, deps, packages: pkgDirs.length, tests: Math.floor(tests / 10) * 10 };
}

if (import.meta.main) {
  const stats = await computeStats();
  // A .js module (not .json) so the dev server serves it to the browser with
  // no JSON import-attribute dance, and the bundler inlines it either way.
  writeFileSync(
    resolve(import.meta.dir, '..', 'src', 'stats.js'),
    `// Generated by scripts/gen-stats.js — do not edit.\nexport default ${JSON.stringify(stats)};\n`,
  );
  console.log('[gen-stats]', JSON.stringify(stats));
}
