name = "Spark"
grammar = "svelte"
path_suffixes = ["html"]
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "<", end = ">", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]
